### PR TITLE
Fix #58

### LINKED ISSUE #58: New builds of 7h/gl dont process scene.bin
Confirmed working on public build 1.54.

I will provide files to make this easier to test and debug, in the provided save file load up the first slot in train graveyard, and run around to generate a random fight, you want to spawn two ghosts and a deenglow (I get this first time every time in all my tests so far), its a common spawn.  The deenglow if the scene.bin is processed will be level 99 and have a turbo ether as the steal item.  If it attacks it will do a "lot" of damage over 300 or over 700 on a crit.  On stock scene.bin if the file fails to process, it will only do around 24 damage, and have an ether for steal.

Files attached are a iro (in folder format) for testing, and save file.

I tested on my trueodin custom build, fork made by unabomb and the canary build, all 3 builds have the same problem, tested with 0.96 opengl driver, but works on 1.54 with aali driver.

I am also supplying the debug log, this log only has the iro loaded so is clean of other mods, I observed in the log it searches for kernel.bin and kernel2.bin, but doesnt search for scene.bin.

The debug log is from my older trueodin build as the 2 newer builds both crash when generating the log. (seperate issue)

[save00.zip](https://github.com/FFT-Hackers/7h/files/3907253/save00.zip)
[ChrisBalance.zip](https://github.com/FFT-Hackers/7h/files/3907255/ChrisBalance.zip)
[log.txt](https://github.com/FFT-Hackers/7h/files/3907262/log.txt)

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
If the desired path to be opened does not contain the game directory inside of it, the file is usually skipped.
This patch now matches these kind of files to the game directory contents. If there is a match, it's definitely a game file.

### CODE REVIEW

File: 7thWrapperLib/Wrap.cs [hunk 1]
```diff
@@ -488,11 +488,11 @@ public enum EMoveMethod : uint {
 
 
             bool result = Win32.WriteFile(hFile, lpBuffer, nNumberOfBytesToWrite, out lpNumberOfBytesWritten, ref lpOverlapped);
-            System.Diagnostics.Debug.WriteLine(String.Format("Write {0} bytes on {1}", lpNumberOfBytesWritten, hFile.ToInt32()));
+            //System.Diagnostics.Debug.WriteLine(String.Format("Write {0} bytes on {1}", lpNumberOfBytesWritten, hFile.ToInt32()));
 
             if (_saveFiles.ContainsKey(hFile)) {
                 int offset = SetFilePointer(hFile, 0, IntPtr.Zero, EMoveMethod.Current);
-                System.Diagnostics.Debug.WriteLine(String.Format("Write {0} bytes to {1} at offset {2}", lpNumberOfBytesWritten, _saveFiles[hFile], offset));
+                //System.Diagnostics.Debug.WriteLine(String.Format("Write {0} bytes to {1} at offset {2}", lpNumberOfBytesWritten, _saveFiles[hFile], offset));
```
Comment (julianxhokaxhiu) [inline 7thWrapperLib/Wrap.cs:495]: I commented those lines because they were bringing a lot of noise in TurboLog, and also it slows down a lot the game while having Turbolog opened. In case they are needed just let me know, but honestly, as we dump failures now, it's not really required to highlight what is being patched.
